2025/02/25 02:51:57 [error] 24#24: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: apim.localhost, request: "GET /authenticationendpoint/login.do?client_id=QJ3OaP661pBZPhuzYfv1TVesKXga&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Fwso2_apim%3A9443%2Fdevportal%2Fservices%2Fauth%2Fcallback%2Flogin&response_type=code&scope=apim%3Aadmin+apim%3Aapi_key+apim%3Aapp_import_export+apim%3Aapp_manage+apim%3Astore_settings+apim%3Asub_alert_manage+apim%3Asub_manage+apim%3Asubscribe+openid&state=%2Fapis&tenantDomain=carbon.super&sessionDataKey=0aa7500f-5758-4aa6-b2d2-dd684c00ad24&relyingParty=QJ3OaP661pBZPhuzYfv1TVesKXga&type=oidc&sp=apim_devportal&isSaaSApp=true&authenticators=BasicAuthenticator%3ALOCAL HTTP/1.1", upstream: "https://172.23.0.2:9443/authenticationendpoint/login.do?client_id=QJ3OaP661pBZPhuzYfv1TVesKXga&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Fwso2_apim%3A9443%2Fdevportal%2Fservices%2Fauth%2Fcallback%2Flogin&response_type=code&scope=apim%3Aadmin+apim%3Aapi_key+apim%3Aapp_import_export+apim%3Aapp_manage+apim%3Astore_settings+apim%3Asub_alert_manage+apim%3Asub_manage+apim%3Asubscribe+openid&state=%2Fapis&tenantDomain=carbon.super&sessionDataKey=0aa7500f-5758-4aa6-b2d2-dd684c00ad24&relyingParty=QJ3OaP661pBZPhuzYfv1TVesKXga&type=oidc&sp=apim_devportal&isSaaSApp=true&authenticators=BasicAuthenticator%3ALOCAL", host: "apim.localhost", referrer: "https://apim.localhost/devportal/apis"
2025/02/25 02:51:58 [error] 24#24: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: apim.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "https://172.23.0.2:9443/favicon.ico", host: "apim.localhost", referrer: "https://apim.localhost/authenticationendpoint/login.do?client_id=QJ3OaP661pBZPhuzYfv1TVesKXga&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Fwso2_apim%3A9443%2Fdevportal%2Fservices%2Fauth%2Fcallback%2Flogin&response_type=code&scope=apim%3Aadmin+apim%3Aapi_key+apim%3Aapp_import_export+apim%3Aapp_manage+apim%3Astore_settings+apim%3Asub_alert_manage+apim%3Asub_manage+apim%3Asubscribe+openid&state=%2Fapis&tenantDomain=carbon.super&sessionDataKey=0aa7500f-5758-4aa6-b2d2-dd684c00ad24&relyingParty=QJ3OaP661pBZPhuzYfv1TVesKXga&type=oidc&sp=apim_devportal&isSaaSApp=true&authenticators=BasicAuthenticator%3ALOCAL"
2025/02/25 02:52:18 [error] 21#21: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: apim.localhost, request: "GET /devportal HTTP/1.1", upstream: "https://172.23.0.2:9443/devportal", host: "apim.localhost"
2025/02/25 02:52:18 [error] 21#21: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: apim.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "https://172.23.0.2:9443/favicon.ico", host: "apim.localhost", referrer: "https://apim.localhost/devportal"
2025/02/25 02:52:22 [error] 21#21: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: apim.localhost, request: "GET /devportal HTTP/1.1", upstream: "https://172.23.0.2:9443/devportal", host: "apim.localhost"
2025/02/25 02:52:22 [error] 21#21: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: apim.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "https://172.23.0.2:9443/favicon.ico", host: "apim.localhost", referrer: "https://apim.localhost/devportal"
